#!/usr/bin/env python3
"""Generate the reusable org-kit documents from company_profile.json.

Every grant application reuses most of the same content. These files are the
canonical source for that content; per-application drafts copy from here and
tailor, so a fact is corrected in one place rather than fifteen.

Anything this script cannot source from company_profile.json is written as an
explicit [[PLACEHOLDER: ...]] token. Nothing is invented — invented figures in
a grant application are fraud, and a reviewer who catches one discards the
whole submission.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).parent
KIT = HERE / "org_kit"
PROFILE = json.loads((HERE.parent / "company_profile.json").read_text())

NAME = PROFILE["company_name"]
EIN = PROFILE["ein_or_registration_number"]
MISSION = PROFILE["mission_summary"]
FOCUS = PROFILE["focus_areas"]
HOME = PROFILE["home_base"]
AREAS = PROFILE["service_areas"]
BUDGET = PROFILE["annual_budget_usd"]

HEADER = (
    "<!-- Generated by build_org_kit.py from company_profile.json.\n"
    "     Edit the PLACEHOLDER values directly in this file; re-running the\n"
    "     script will overwrite it, so copy custom edits into the script or\n"
    "     into a per-application draft. -->\n\n"
)

FILES = {}

FILES["00-README.md"] = f"""# Org kit — {NAME}

The reusable core of every grant application. Per-application drafts copy from
these files and tailor; the canonical fact lives here.

## Before the first submission

Search every file for `[[PLACEHOLDER` and fill it in. The count is deliberate —
these are facts only the organization holds, and none of them may be guessed.
The highest-priority ones, because nearly every funder asks:

1. **UEI** (Unique Entity Identifier from SAM.gov) — required on all federal forms
2. **Board roster** — names, roles, affiliations
3. **Key staff** — names, credentials, FTE
4. **Served numbers** — how many people, over what period
5. **Outcome data** — what changed for them
6. **Budget detail** — the ${BUDGET:,} broken into revenue and expense lines
7. **Fiscal documents** — most recent 990, audit or review, board-approved budget

## Rule

Never submit a number this kit cannot source. If a funder asks for data the
organization does not track, say so and describe what it does track. Reviewers
routinely forgive a young organization's thin data; they do not forgive
invented data.
"""

FILES["01-organization-profile.md"] = HEADER + f"""# Organization profile

The block of facts nearly every application form asks for. Keep this current;
everything else references it.

| Field | Value |
|---|---|
| Legal name | {NAME} |
| EIN | {EIN} |
| UEI (SAM.gov) | [[PLACEHOLDER: UEI — 12 characters, from your SAM.gov entity record]] |
| Organization type | 501(c)(3) nonprofit |
| Year founded | [[PLACEHOLDER: year of incorporation]] |
| Date of 501(c)(3) determination | [[PLACEHOLDER: from IRS determination letter]] |
| Street address | [[PLACEHOLDER: street]], {HOME['city']}, {HOME['state_or_region']} [[PLACEHOLDER: ZIP]] |
| Mailing address | [[PLACEHOLDER: if different from above]] |
| Congressional district | [[PLACEHOLDER: required on most federal forms — look up by ZIP]] |
| County | {HOME['state_or_region']} — [[PLACEHOLDER: county of the HQ address]] |
| Main phone | [[PLACEHOLDER]] |
| Website | [[PLACEHOLDER]] |
| Primary contact | [[PLACEHOLDER: name, title, email, direct phone]] |
| Authorized Organization Representative (AOR) | [[PLACEHOLDER: name and title of the person who certifies federal submissions]] |
| Fiscal year end | [[PLACEHOLDER: e.g. December 31]] |
| Annual operating budget | ${BUDGET:,} |
| DUNS/legacy identifiers | [[PLACEHOLDER: only if a funder still asks]] |

## Service area

Headquartered in {HOME['city']}, {HOME['state_or_region']}. Serves
{", ".join(AREAS)}.

Priority counties are Essex, Bergen, Union, and Somerset; the organization is
eligible statewide and also serves surrounding counties.

## Registrations

| Registration | Status | Expires | Notes |
|---|---|---|---|
| SAM.gov | Active (confirmed 2026-08-20) | [[PLACEHOLDER: renewal date — SAM expires annually]] | Required for all federal applications |
| Grants.gov | [[PLACEHOLDER: confirm active with an authorized AOR]] | — | Separate from SAM; AOR authorization can take days |
| NJ charitable registration | [[PLACEHOLDER: NJ Division of Consumer Affairs registration number]] | [[PLACEHOLDER]] | Required to solicit in NJ |
"""

FILES["02-mission-and-boilerplate.md"] = HEADER + f"""# Mission and boilerplate

Funders ask for the organization description at wildly different lengths. These
are pre-cut so nobody rewrites the mission at 11pm the night before a deadline.

## Full mission statement

{MISSION}

## 25 words

{NAME} interrupts the cycle of mental illness, substance use, trauma, and
incarceration in New Jersey through trauma-informed behavioral health education
and wraparound support.

## 50 words

{NAME} is a New Jersey nonprofit interrupting the intersecting cycle of mental
illness, substance use disorder, trauma, and justice involvement. Through
trauma-informed, evidence-based psychoeducation and wraparound support, it
serves individuals and families across the full continuum — prevention through
reentry and reintegration — in partnership with NJ courts and treatment
providers.

## 100 words

{NAME} interrupts the intersecting cycle of mental illness, substance use
disorder, trauma, and justice involvement in New Jersey communities. It
delivers trauma-informed, evidence-based behavioral health education,
psychoeducation, and wraparound support to individuals and families across the
full continuum, from prevention through reentry and reintegration, drawing on
Trauma-Informed Care, CBT, EMDR, Motivational Interviewing, and Seeking Safety.
The organization is grounded in founder Dr. John A. Gore III's lived experience
with homelessness and incarceration combined with a decade of clinical
expertise, and works through established partnerships with New Jersey courts,
recovery courts, the IDRC, and care management organizations to reach
populations traditional systems miss.

## One-line descriptor

A New Jersey nonprofit delivering trauma-informed behavioral health education
and reentry support to justice-involved individuals and their families.

## Tagline options

[[PLACEHOLDER: if the organization has an approved tagline, put it here so it
is used consistently]]
"""

FILES["03-statement-of-need.md"] = HEADER + f"""# Statement of need

The section funders weigh most heavily, and the one most often written badly.
It must connect *documented* population-level need to *this organization's*
specific service area and population.

## Structure that works

1. **The problem, at population scale** — cite state or county data
2. **Why the priority counties specifically** — local numbers beat state numbers
3. **The service gap** — what existing systems miss, and why
4. **Why this organization is positioned to close it** — partnerships, access,
   credibility with the population
5. **What happens without funding**

## Data to gather and keep current

Every figure below needs a citation with a year. Rotate them annually — a
reviewer who spots a 2019 statistic in a 2027 application reads it as
inattention.

| Data point | Source to pull from | Current value |
|---|---|---|
| NJ overdose deaths, most recent year | NJ Cares / NJ Dept. of Health | [[PLACEHOLDER]] |
| Overdose deaths in Essex, Bergen, Union, Somerset | NJ Cares county dashboard | [[PLACEHOLDER]] |
| NJ prison releases per year | NJ DOC annual report | [[PLACEHOLDER]] |
| NJ recidivism rate (3-year) | NJ DOC recidivism report | [[PLACEHOLDER]] |
| Share of justice-involved with SUD or co-occurring disorder | SAMHSA / BJS | [[PLACEHOLDER]] |
| NJ residents with unmet behavioral health treatment need | SAMHSA NSDUH state tables | [[PLACEHOLDER]] |
| Recovery court participants in priority counties | NJ Courts | [[PLACEHOLDER]] |
| Racial disparities in NJ incarceration | Sentencing Project / NJ DOC | [[PLACEHOLDER]] |

## The organization's distinctive argument

Three things differentiate this applicant, and each should appear in every
statement of need:

**Reach into a population traditional systems miss.** Established referral
relationships with NJ courts, recovery courts, the IDRC, and care management
organizations mean the organization meets people at mandated touchpoints rather
than waiting for voluntary engagement.

**Credibility grounded in lived experience.** Founder Dr. John A. Gore III
brings direct experience of homelessness and incarceration alongside a decade of
clinical expertise. For a justice-involved population with well-documented
distrust of clinical systems, this is a service-delivery asset, not a
biographical detail — say so explicitly rather than leaving it implied.

**Full-continuum coverage.** Prevention through reentry and reintegration, in
one organization, rather than a handoff between agencies at the point clients
are most likely to disengage.

## Language notes

- Person-first throughout: "people who are incarcerated," not "inmates";
  "person with a substance use disorder," not "addict."
- "Justice-involved" is the standard term; "offender" reads as dated and
  appears in scoring rubrics as a negative.
- Name the evidence base by name — TIC, CBT, EMDR, Motivational Interviewing,
  Seeking Safety — since reviewers scan for recognized modalities.
"""

FILES["04-program-descriptions.md"] = HEADER + f"""# Program descriptions

The three service lines, in the organization's own framing. Tailor emphasis per
funder; do not restate a program as something it is not to fit a solicitation.

"""

for i, area in enumerate(FOCUS, 1):
    title = area.split("—")[0].strip() if "—" in area else area[:60]
    body = area.split("—", 1)[1].strip() if "—" in area else area
    FILES["04-program-descriptions.md"] += f"""## {i}. {title}

{body}

- **Population served:** [[PLACEHOLDER: who, and roughly how many per year]]
- **Delivery format:** [[PLACEHOLDER: group size, session length, series length, setting]]
- **Referral sources:** [[PLACEHOLDER: which courts, IDRC, CMOs, self-referral]]
- **Evidence base:** [[PLACEHOLDER: which of TIC / CBT / EMDR / MI / Seeking Safety applies here]]
- **Staffing:** [[PLACEHOLDER: who delivers it, credentials, FTE]]
- **Outcomes tracked:** [[PLACEHOLDER: what is measured and how]]

"""

FILES["04-program-descriptions.md"] += """## Scope boundary — read before tailoring

The organization delivers **education, psychoeducation, and wraparound support**,
and **connects clients to** outpatient and intensive outpatient treatment. It
does not itself provide clinical SUD treatment.

Several solicitations on the pipeline are titled as treatment programs. Do not
describe the organization as a treatment provider to fit one. Either confirm the
funder accepts a referral-partner structure, or apply with a treatment provider
as partner. Misrepresenting the service model is both a scoring risk and, in a
federal application, a false statement.
"""

FILES["05-people.md"] = HEADER + f"""# Leadership, staff, and board

Almost every application asks for these in some form; federal applications
usually want résumés or biosketches as attachments.

## Founder / Executive Director

**Dr. John A. Gore III**

- Title: [[PLACEHOLDER: exact title]]
- Credentials: [[PLACEHOLDER: degrees, licenses, license numbers and states]]
- Years in field: approximately a decade of clinical expertise
- Lived experience: homelessness and incarceration — a documented asset for
  engagement with this population
- Bio, 100 words: [[PLACEHOLDER]]
- Bio, 250 words: [[PLACEHOLDER]]
- Résumé on file: [[PLACEHOLDER: path to current CV]]

## Key staff

| Name | Title | Credentials | FTE | Role on grant-funded work |
|---|---|---|---|---|
| [[PLACEHOLDER]] | | | | |

If the organization is currently founder-led with contracted facilitators, say
that plainly and describe the contractor bench. Reviewers accept lean staffing
in a young organization; they penalize vagueness about who actually does the
work.

## Board of directors

| Name | Role | Affiliation | Term |
|---|---|---|---|
| [[PLACEHOLDER]] | | | |

- Board size: [[PLACEHOLDER]]
- Meeting frequency: [[PLACEHOLDER]]
- Conflict-of-interest policy on file: [[PLACEHOLDER: yes/no + date adopted]]

## Advisory / clinical supervision

[[PLACEHOLDER: any clinical supervisor, advisory board, or consulting
psychiatrist — relevant to funders who require clinical oversight]]
"""

FILES["06-logic-model-and-evaluation.md"] = HEADER + """# Logic model and evaluation plan

Two of the most commonly requested and most commonly weak sections. A funder
reading a vague evaluation plan assumes the organization will not know whether
its program worked — and neither will they.

## Logic model skeleton

| | |
|---|---|
| **Inputs** | Staff and facilitators, curriculum, court/IDRC referral partnerships, treatment provider relationships, facilities, funding |
| **Activities** | [[PLACEHOLDER: workshops delivered, one-on-one support sessions, referrals made, family sessions]] |
| **Outputs** | [[PLACEHOLDER: # participants, # sessions, # referrals completed, # families served]] |
| **Short-term outcomes** | [[PLACEHOLDER: knowledge gain, treatment engagement, reduced symptom severity]] |
| **Intermediate outcomes** | [[PLACEHOLDER: treatment retention, stable housing, employment, reduced violations]] |
| **Long-term outcomes** | [[PLACEHOLDER: reduced recidivism, sustained recovery, family stability]] |

## Measurement

| Outcome | Instrument | When collected | Who collects |
|---|---|---|---|
| [[PLACEHOLDER]] | [[PLACEHOLDER: pre/post survey, standardized instrument, court records]] | | |

Validated instruments are worth naming if used — reviewers recognize them and
they signal methodological seriousness. If the organization uses informal
pre/post surveys, say so honestly and describe plans to strengthen measurement.

## Data infrastructure

- Case management or data system in use: [[PLACEHOLDER]]
- Who enters data, and when: [[PLACEHOLDER]]
- How participant privacy and 42 CFR Part 2 obligations are handled:
  [[PLACEHOLDER — this matters: SUD treatment records carry confidentiality
  requirements stricter than HIPAA, and federal reviewers look for awareness of it]]

## Honest positioning for a young organization

If longitudinal outcome data does not exist yet, do not manufacture it. Write:
what is currently tracked, what the grant period would let the organization
begin tracking, and the specific plan for doing so. A credible plan to build
measurement beats a fabricated result, and it survives a site visit.
"""

FILES["07-budget.md"] = HEADER + f"""# Budget templates and narrative

## Organizational budget

Total annual operating budget: **${BUDGET:,}**

| Revenue source | Amount | % of total |
|---|---|---|
| [[PLACEHOLDER: grants, contracts, fee-for-service, donations]] | | |
| **Total** | ${BUDGET:,} | 100% |

| Expense category | Amount | % of total |
|---|---|---|
| Personnel (salaries + fringe) | [[PLACEHOLDER]] | |
| Contracted services | [[PLACEHOLDER]] | |
| Program supplies and curriculum | [[PLACEHOLDER]] | |
| Occupancy | [[PLACEHOLDER]] | |
| Travel | [[PLACEHOLDER]] | |
| Insurance | [[PLACEHOLDER]] | |
| Administrative / indirect | [[PLACEHOLDER]] | |
| **Total** | ${BUDGET:,} | 100% |

## Project budget template

Standard federal categories. Foundations usually accept a simplified version.

| Category | Year 1 | Basis for the figure |
|---|---|---|
| Personnel | | list each position, salary, % FTE on this project |
| Fringe benefits | | state the fringe rate and how it was derived |
| Travel | | mileage rate, # trips, purpose |
| Equipment | | items over $5,000 unit cost |
| Supplies | | |
| Contractual | | each contractor, scope, rate |
| Other | | |
| **Total direct** | | |
| Indirect | | see rate note below |
| **TOTAL** | | |

## Indirect cost rate — decide this once

Federal awards let an organization without a negotiated rate elect the **10%
de minimis** rate on modified total direct costs. Two things follow:

1. Elect it. Declining indirect costs does not make an application more
   competitive; it makes the organization absorb real overhead it cannot afford
   at this budget size.
2. If a negotiated indirect cost rate agreement is ever obtained, record it
   here: [[PLACEHOLDER: NICRA rate and agreement date, if any]]

## Budget narrative rules

- Every line traces to a program activity described elsewhere in the application.
- Show the arithmetic: "0.25 FTE Program Coordinator at $52,000 = $13,000,"
  not "$13,000."
- Match requirements: check each solicitation. Note here which pipeline grants
  require match: [[PLACEHOLDER]]
- **Cash flow:** most federal awards reimburse after spending. At a
  ${BUDGET:,} budget, a large cost-reimbursement award creates a real payroll
  float problem. Before accepting one, confirm a line of credit or bridge
  source: [[PLACEHOLDER: what covers the gap]]
"""

FILES["08-attachments-checklist.md"] = HEADER + """# Standard attachments

The documents funders request repeatedly. Keep current PDFs in
`org_kit/attachments/` so no application waits on document retrieval.

| Document | Status | File | Expires / refresh |
|---|---|---|---|
| IRS 501(c)(3) determination letter | [[PLACEHOLDER]] | | never |
| W-9 | [[PLACEHOLDER]] | | when info changes |
| Most recent Form 990 | [[PLACEHOLDER]] | | annually |
| Audited financials or financial review | [[PLACEHOLDER]] | | annually |
| Board-approved current-year budget | [[PLACEHOLDER]] | | annually |
| Board roster with affiliations | [[PLACEHOLDER]] | | annually |
| Organizational chart | [[PLACEHOLDER]] | | as staffing changes |
| Key staff résumés / biosketches | [[PLACEHOLDER]] | | annually |
| Certificate of insurance (general liability) | [[PLACEHOLDER]] | | annually |
| Professional liability insurance | [[PLACEHOLDER]] | | annually |
| NJ charitable registration | [[PLACEHOLDER]] | | annually |
| SAM.gov registration confirmation | Active as of 2026-08-20 | | annually |
| Conflict of interest policy | [[PLACEHOLDER]] | | on revision |
| Non-discrimination / EEO policy | [[PLACEHOLDER]] | | on revision |
| Letters of support / MOUs from partners | [[PLACEHOLDER]] | | per application |
| Logic model | see 06 | | per application |
| Indirect cost rate agreement, if any | [[PLACEHOLDER]] | | per agreement |

## Note on letters of support

These are the single most common cause of a missed deadline, because they
depend on other people. Request them **three weeks out**, not one. Send each
partner a draft they can edit — a court administrator will sign a good draft
far faster than they will write one.

Standing partners to approach: [[PLACEHOLDER: named contacts at NJ recovery
courts, IDRC, care management organizations, treatment providers]]
"""

FILES["09-partnerships.md"] = HEADER + """# Partnerships and referral relationships

The organization's core competitive asset, and the thing most applications
under-document. Reviewers discount claimed partnerships that carry no evidence.

| Partner | Type | Relationship | Contact | MOU on file? | Will provide letter? |
|---|---|---|---|---|---|
| [[PLACEHOLDER: specific NJ recovery court]] | Court | Referral source | | | |
| [[PLACEHOLDER: IDRC office]] | State program | Referral source | | | |
| [[PLACEHOLDER: care management organizations]] | CMO | Referral / coordination | | | |
| [[PLACEHOLDER: outpatient/IOP providers]] | Treatment | Referral destination | | | |

## Why this table matters more than it looks

Two pipeline items turn on it directly:

- **BJA Crisis Stabilization and Community Reentry** *requires* nonprofit
  applicants to apply in partnership with the relevant criminal justice agency.
  A documented court relationship is the eligibility criterion.
- **Both Second Chance Act tracks** are stronger as partnership or sub-award
  bids than solo applications at this budget size.

Formalizing even two of these relationships as written MOUs would materially
improve federal competitiveness. That is a weeks-long task worth starting
before it is needed.
"""

FILES["10-sustainability-and-capacity.md"] = HEADER + f"""# Sustainability and organizational capacity

## Sustainability

Nearly every funder asks how the work continues after the grant ends. The weak
answer is "we will seek additional grants." Stronger elements:

- Diversified revenue: [[PLACEHOLDER: current mix]]
- Fee-for-service or contract revenue from courts, CMOs, or treatment providers:
  [[PLACEHOLDER: existing or planned]]
- In-kind support: [[PLACEHOLDER: donated space, volunteer facilitators]]
- Institutionalization: which partners would absorb or continue elements of the
  program: [[PLACEHOLDER]]

## Capacity — including the honest limits

Federal reviewers weigh organizational capacity heavily, and at a
${BUDGET:,} budget the honest position is a young, focused organization with
deep population access and lean infrastructure. Two implications:

1. **Right-size the ask.** Requesting three times annual budget invites
   capacity scrutiny that a smaller request does not. Ask well under a
   solicitation's ceiling unless the capacity case is genuinely there.
2. **Federal reentry programs commonly expect 2-3 years of operational history**
   in justice-related programming. Confirm the organization clears that bar
   before investing in a solo federal application:
   [[PLACEHOLDER: years of operation in justice-related programming]]

## Fiscal controls

- Accounting system: [[PLACEHOLDER]]
- Who reconciles accounts: [[PLACEHOLDER]]
- Single audit status: an organization expending $1,000,000+ in federal funds
  in a fiscal year triggers a Single Audit. Note current status:
  [[PLACEHOLDER]] — this is directly relevant to the $1M pipeline items.
"""

def main():
    KIT.mkdir(parents=True, exist_ok=True)
    (KIT / "attachments").mkdir(exist_ok=True)
    (KIT / "attachments" / ".gitkeep").write_text("")
    for name, body in FILES.items():
        (KIT / name).write_text(body)
    total = sum(f.read_text().count("[[PLACEHOLDER") for f in KIT.glob("*.md"))
    print(f"wrote {len(FILES)} org-kit files to {KIT}")
    print(f"placeholders to fill: {total}")


if __name__ == "__main__":
    main()
